# Copyright © 2026 Gauthameshwar and ProcessTensors.jl contributors #src
# SPDX-License-Identifier: MIT #src
# #src
# File: docs/literate/examples/ramsey_povm.jl #src
# Contributor: Gauthameshwar S. #src
# #src
# Repeated Ramsey readouts with active reset on a non-Markovian process tensor. #src

# # Ramsey readouts as a probe of bath memory
#
# A reduced trajectory answers a passive question: *what state does the system
# occupy at each time if we leave it alone?* A process tensor can answer a more
# experimental one: *what are the joint statistics of several interventions
# performed on the same open system?*
#
# We demonstrate that distinction with a three-shot Ramsey protocol. After each
# Ramsey interval the qubit is measured in the ``X`` basis and immediately reset
# to the same state before the next round. The reset deliberately erases the
# qubit's own local history. If correlations nevertheless remain between the
# three measurement records, they must have survived outside the qubit and
# returned through the environment.
#
# This turns a familiar Ramsey experiment into a direct probe of temporal
# memory.
#
# !!! related "Related material"
#     - Tutorial: [Construct your first process tensor](@ref)
#     - Theory: [Process Tensors](../theory/process_tensors.md)
#
# !!! script "Companion script"
#     The protocol diagram and outcome-probability figures are generated by
#     [`scripts/ramsey_povm.jl`](https://github.com/Gauthameshwar/ProcessTensors.jl/blob/main/scripts/ramsey_povm.jl).
#
# ## Setup

using Logging
using Printf
using ITensors
using ITensors.Ops: Trotter
using ProcessTensors

# ## The noisy Ramsey experiment
#
# The processor is a qubit coupled through ``Z`` to a thermal bosonic
# environment,
#
# ```math
# H_E=\sum_k\omega_k b_k^\dagger b_k,
# \qquad
# H_{SE}
# =
# Z\sum_k g_k(b_k+b_k^\dagger).
# ```
#
# We choose the Ohmic spectral density
#
# ```math
# J(\omega)=2\alpha\omega e^{-\omega/\omega_c},
# ```
#
# and discretize it on midpoint frequencies,
#
# ```math
# \omega_k=\left(k-\frac12\right)\Delta\omega,
# \qquad
# g_k=\sqrt{J(\omega_k)\Delta\omega}.
# ```
#
# The coupling commutes with ``Z``, so the bath produces pure dephasing: it
# records phase information without directly exchanging qubit population.
#
# A Ramsey round begins by preparing
#
# ```math
# \rho_{\mathrm r}=|+\rangle_x\langle+|,
# ```
#
# letting the qubit dephase for a fixed time, and reading it out along ``X``.
# The usual Ramsey preparation and analysis pulses are absorbed here into the
# ``|+\rangle`` preparation and the final ``X``-basis POVM.
#
# Rather than assuming a perfectly sharp detector, we use
#
# ```math
# E_x^{(\eta)}
# =
# \frac12\left(I+x\eta X\right),
# \qquad
# x\in\{-1,+1\}.
# ```
#
# The parameter ``η`` is the measurement visibility or sharpness:
# ``η=1`` gives an ideal projective ``X`` readout, while ``η=0`` carries no
# information about the qubit because it results in a 50-50 probability of the 
# actual state being either +1 or -1. We use ``η=0.90``.

# ### Why reset after every measurement?
#
# A POVM element determines an outcome probability, but by itself does not say
# which state enters the next round. We therefore follow every readout with the
# same active reset ``ρ_r``. The complete outcome-conditioned operation is
#
# ```math
# \mathcal A_x^{\mathrm{MR}}(\rho)
# =
# \operatorname{Tr}\!\left[E_x^{(\eta)}\rho\right]\rho_{\mathrm r}
# = |E_x^{(\eta)}\rangle\!\rangle \langle\!\langle\rho_{\mathrm r}|.
# ```
#
# Summing over outcomes gives
#
# ```math
# \sum_x\mathcal A_x^{\mathrm{MR}}(\rho)
# =
# \operatorname{Tr}(\rho)\rho_{\mathrm r},
# ```
#
# a CPTP replacement channel. This measure and reprepare creates a **causal break**: after it acts, the
# future qubit state contains no information about the qubit state immediately
# before the measurement.
#
# That is precisely what makes the protocol interesting. For a memoryless
# process, three identically timed measure-and-reset rounds are independent and
#
# ```math
# p(x_1,x_2,x_3)
# =
# p_1(x_1)p_2(x_2)p_3(x_3).
# ```
#
# A non-Markovian bath can violate this factorization because the reset acts
# only on the qubit. Environmental degrees of freedom may still remember the
# earlier rounds.
#
# ![Three repeated Ramsey readouts with active reset](../assets/examples/ramsey_povm_protocol.png)
#
# The timeline makes the causal structure explicit. The qubit is prepared in
# ``ρ_r``, exposed to the same process tensor, measured, and reset three times.
# The green connection remains present throughout: resetting the qubit does
# **not** reset the thermal bath.

# ## Construct the dephasing process tensor
#
# The documentation grid is deliberately short: two process-tensor steps
# between readouts, a small ACE bond cap, and the same four-mode Ohmic bath
# used by the companion script. The companion calculation uses a longer
# chain and a larger `maxdim`.

const N_BATH = 4
const LOCAL_DIM = 3
const ALPHA = 0.20
const OMEGA_C = 4.0
const OMEGA_MAX = 20.0
const TEMPERATURE = 2.5

const DT = 0.10
const NSTEPS = 7
const ACE_CUTOFF = 1e-5
const ACE_MAXDIM = 32

frequency_spacing = OMEGA_MAX / N_BATH
frequencies = [
    (k - 0.5) * frequency_spacing
    for k in 1:N_BATH
]
spectral_weights =
    2 * ALPHA .* frequencies .* exp.(-frequencies ./ OMEGA_C)
couplings = sqrt.(spectral_weights .* frequency_spacing)

# The qubit has no free Hamiltonian in this protocol. During every idle Ramsey
# interval, its dynamics therefore comes entirely from the dephasing bath.

system_sites = siteinds("Qubit", 1)
system = qubit_system(system_sites);

# Each oscillator begins in a truncated Gibbs state
#
# ```math
# \rho_k^{\mathrm{th}}
# =
# \frac{1}{Z_k}
# \sum_{n=0}^{M-1}
# e^{-n\omega_k/T}|n\rangle\langle n|,
# ```
#
# where ``\hbar=k_B=1``. [`thermal_mode`](@ref) builds that state from the
# local oscillator Hamiltonian. Its coupling `OpSum` uses local site `1` for
# the oscillator and local site `2` for the processor qubit.

bath_sites = siteinds("Boson", N_BATH; dim=LOCAL_DIM)
bath_liouville_sites = liouv_sites(bath_sites)

modes = [
    let
        ωk = frequencies[k]
        gk = couplings[k]

        mode_hamiltonian = OpSum()
        mode_hamiltonian += ωk, "N", 1

        coupling = OpSum()
        coupling += gk, "A", 1, "Z", 2
        coupling += gk, "Adag", 1, "Z", 2

        thermal_mode(
            [bath_liouville_sites[k]],
            mode_hamiltonian,
            TEMPERATURE;
            coupling=coupling,
        )
    end for k in 1:N_BATH
];

bath = with_logger(NullLogger()) do
    bosonic_bath(modes)
end;

println("Repeated-Ramsey process")
@printf("  bath modes:                    %d\n", N_BATH)
@printf("  local boson dimension:         %d\n", LOCAL_DIM)
@printf("  α, ωc:                         %.2f, %.2f\n", ALPHA, OMEGA_C)
@printf("  temperature:                   %.2f\n", TEMPERATURE)
@printf("  dt, nsteps:                    %.2f, %d\n", DT, NSTEPS)
@printf("  ACE cutoff:                    %.1e\n", ACE_CUTOFF)

build_time = @elapsed begin
    process_tensor = build_process_tensor(
        system;
        method=ACE(
            cutoff=ACE_CUTOFF,
            maxdim=ACE_MAXDIM,
        ),
        environment=bath,
        dt=DT,
        nsteps=NSTEPS,
        sys_alg=Trotter{2}(),
        combine_alg=Trotter{2}(),
        progress=false,
    )
end

println(process_tensor)
@printf("  maximum PT bond dimension:     %d\n", maxlinkdim(process_tensor))
@printf("  PT build time:                 %.3f s\n", build_time)

# ## Turn the POVM and reset into one instrument
#
# `ProcessTensors.jl` represents the two pieces separately:
#
# - [`observable_measurement`](@ref) places the effect ``E_x`` on the output leg;
# - [`state_preparation`](@ref) places ``ρ_r`` on the following input leg.
#
# Multiplying opposite-leg instruments creates the two-leg
# [`ProductInstrument`](@ref) corresponding exactly to
# ``\mathcal A_x^{MR}``.

const ETA = 0.90
const OUTCOMES = (-1, 1)

rho_reset = to_dm(MPS(system_sites, ["+"]))

effects = Dict(
    x => OpSum() +
        (1 / 2, "Id", 1) +
        (x * ETA / 2, "X", 1)
    for x in OUTCOMES
)

ramsey_instruments = Dict(
    x => observable_measurement(effects[x]) *
         state_preparation(rho_reset)
    for x in OUTCOMES
);

# Three readouts are separated by two process-tensor time steps. Since
# ``DT=0.10``, each Ramsey interval lasts ``2DT=0.20`` in the natural time
# units of the simulation.

const READOUT_STEPS = (2, 4, 6)
ramsey_interval = 2 * DT

@printf("Ramsey interval between readouts: %.2f\n", ramsey_interval)

# ### Write one experimental record as an `InstrumentSeq`
#
# Consider the record ``(+,-,+)``. We prepare the qubit at the first input,
# insert the outcome-conditioned measure-and-reset operation at each readout,
# and finally trace the open system leg. All unused slots retain the identity
# operation supplied by [`default_schedule`](@ref).

example_record = (1, -1, 1)

example_sequence = default_schedule(process_tensor)
add!(example_sequence, state_preparation(rho_reset), 0)

for (step, outcome) in zip(READOUT_STEPS, example_record)
    add!(
        example_sequence,
        ramsey_instruments[outcome],
        step,
    )
end

add!(
    example_sequence,
    trace_out(),
    process_tensor.nsteps,
)

println(example_sequence)

# Contracting this sequence with the process tensor returns the scalar
#
# ```math
# p(x_1,x_2,x_3)
# =
# \operatorname{Tr}
# \left[
# \mathcal T[
# \mathcal A_{x_3}^{\mathrm{MR}},
# \mathcal A_{x_2}^{\mathrm{MR}},
# \mathcal A_{x_1}^{\mathrm{MR}},
# \mathcal P_{\rho_{\mathrm r}}
# ]
# \right].
# ```
#
# We now repeat the same contraction for all ``2^3=8`` possible records. The
# expensive environment is *not* rebuilt; only the instruments attached to the
# stored temporal legs change.

records = vec(
    collect(
        Iterators.product(
            ntuple(
                _ -> OUTCOMES,
                length(READOUT_STEPS),
            )...,
        ),
    ),
)

probabilities = Float64[]

for record in records
    sequence = default_schedule(process_tensor)
    add!(sequence, state_preparation(rho_reset), 0)

    for (step, outcome) in zip(READOUT_STEPS, record)
        add!(sequence, ramsey_instruments[outcome], step)
    end

    add!(sequence, trace_out(), process_tensor.nsteps)

    value = evaluate_process(
        process_tensor,
        sequence;
        progress=false,
    )

    @assert abs(imag(value)) < 1e-7
    push!(probabilities, real(value))
end

@assert minimum(probabilities) > -1e-7
@assert abs(sum(probabilities) - 1) < 5e-3

# ## Would independent Ramsey shots give the same statistics?
#
# From the eight-record distribution we first calculate the marginal
# probability of each outcome in each round,
#
# ```math
# p_j(x)
# =
# \sum_{\{x_i:i\neq j\}}
# p(x_1,x_2,x_3).
# ```
#
# Their product is the joint distribution predicted for independent rounds.
# Keeping the three marginals separate also avoids assuming stationarity.

marginals = [
    Dict(
        x => sum(
            probabilities[j]
            for j in eachindex(records)
            if records[j][round] == x
        )
        for x in OUTCOMES
    )
    for round in eachindex(READOUT_STEPS)
]

independent_probabilities = [
    prod(
        marginals[round][record[round]]
        for round in eachindex(READOUT_STEPS)
    )
    for record in records
]

@printf("sum of branch probabilities: %.10f\n", sum(probabilities))
println("record     p(PT)       p(marginal)")
for (r, p, q) in zip(records, probabilities, independent_probabilities)
    @printf("p(%s)  %10.8f  %10.8f\n", join(x == 1 ? "+" : "-" for x in r), p, q)
end

# ### The experiment remembers what the qubit forgot
#
# The companion script compares the eight process-tensor records with the
# product of the measured single-round marginals:
#
# ![Outcome-record probabilities versus the product of single-round marginals](../assets/examples/ramsey_povm_records.png)
#
# All eight branch probabilities remain non-negative and sum to one, as required
# for the complete measure-and-reset instrument. But several green and orange
# bars do not coincide.
#
# That mismatch is the point of the experiment. The active reset prevents the
# qubit itself from carrying information from one round into the next. A
# memoryless environment would therefore make the records factorize. Here the
# bath retains information across the causal breaks and feeds it back during
# later Ramsey intervals, producing correlated outcomes.
#
# The deviation from the product distribution is thus an **operational
# signature of non-Markovian memory for this protocol**: the process tensor
# remembers something that the repeatedly reset qubit cannot.
#
# !!! summary "Example takeaways"
#     - Ramsey interferometry can probe a process tensor through repeated
#       outcome-resolved interventions, not only through a reduced trajectory.
#     - An unsharp ``X`` POVM with visibility ``η`` is combined with an active
#       reset to form the causal-break map
#       ``ρ → Tr(E_x ρ) ρ_r`` as a [`ProductInstrument`](@ref).
#     - `default_schedule`, `add!`, and `evaluate_process` translate the
#       laboratory protocol directly into a contraction of the stored PT-MPO.
#     - Because every readout is followed by the same reset, correlations
#       between later records cannot be carried by the qubit's local state.
#     - The observed failure
#       ``p(x_1,x_2,x_3) ≠ p_1(x_1)p_2(x_2)p_3(x_3)`` therefore exposes
#       environmental information retained across the causal breaks.
