# Copyright © 2026 Gauthameshwar and ProcessTensors.jl contributors #src
# SPDX-License-Identifier: MIT #src
# #src
# File: docs/literate/tutorials/06_process_tensor_instruments.jl #src
# Contributor: Gauthameshwar S. #src
# #src
# Probes one fixed spin–boson process tensor with preparations, controls, #src
# measurements, and a causal break. #src

# # Explore a process with instruments
#
# We now keep the process tensor fixed and change the operations applied to the
# spin. The model is the same truncated spin–boson system built in
# [Construct your first process tensor](@ref): one spin, one vacuum boson, and
# the displacement coupling ``g S^z(a + a^\dagger)``.

# ## Setup
#
# This page rebuilds that process tensor so it can be run in a fresh session.
# The parameters match the construction tutorial.

using ITensors
using ProcessTensors
using ITensors.Ops: Exact, Trotter

h = 0.6
ω = 1.1
g = 2.0
n_max = 2
dt = 0.1
nsteps = 8

system_sites = siteinds("S=1/2", 1)

H_S = OpSum()
H_S += h, "Sx", 1
system = spin_system(system_sites, H_S)

boson_sites = siteinds("Boson", 1; dim=n_max + 1)
boson_sites_L = liouv_sites(boson_sites)

H_B = OpSum()
H_B += ω, "N", 1
ρB0_L = to_liouville(to_dm(MPS(boson_sites, ["0"])); sites=boson_sites_L)

H_SB = OpSum()
H_SB += g, "A", 1, "Sz", 2
H_SB += g, "Adag", 1, "Sz", 2

environment = bosonic_bath([
    bosonic_mode(boson_sites_L, H_B, ρB0_L; coupling=H_SB),
])

pt = build_process_tensor(
    system;
    environment=environment,
    dt=dt,
    nsteps=nsteps,
    method=Dense(),
    alg=Exact(),
    sys_alg=Trotter{2}(),
)

ρ_plus = to_dm(MPS(ComplexF64[1, 1] / sqrt(2), system_sites))
ρ_up = to_dm(MPS(system_sites, ["Up"]))
ρ_dn = to_dm(MPS(system_sites, ["Dn"]))

Sz = OpSum()
Sz += 1.0, "Sz", 1
Sz_L = to_liouville(MPO(Sz, system_sites); sites=system.sites)

println("Rebuilt process tensor:")
println(pt)

@assert pt.nsteps == nsteps
@assert pt.dt == dt
@assert abs(tr(ρ_plus) - 1) < 1e-12

# ## [Reduced trajectory](@id evolving-reduced-states)
#
# The first question is the reduced spin trajectory generated by one preparation.
#
# `evolve` is the convenience form of that experiment: prepare the spin, apply
# the identity at the intermediate slots, and leave each output available to
# read. The explicit schedule for the same idea comes in the next sections.
# The preparation here is ``|\uparrow\rangle``.

trajectory = evolve(pt, ρ_up)

println("Sample times:")
println(trajectory.times)

@assert length(trajectory.times) == nsteps
@assert length(trajectory.states_hilbert) == nsteps
@assert all(ρ -> abs(tr(ρ) - 1) < 1e-8, trajectory.states_hilbert)

#-

mz = [
    real(inner(Sz_L, to_liouville(ρ; sites=system.sites)))
    for ρ in trajectory.states_hilbert
]

println("⟨Sz⟩ with the boson:")
println(mz)

@assert all(isfinite, mz)

# A trajectory with no boson shows whether the oscillator influences the spin.
# Build the same spin and the same grid with `environment = nothing`, then call
# `evolve` again.

pt_isolated = build_process_tensor(
    system;
    dt=dt,
    nsteps=nsteps,
    method=Dense(),
    alg=Exact(),
    sys_alg=Trotter{2}(),
)

trajectory_isolated = evolve(pt_isolated, ρ_up)
mz_isolated = [
    real(inner(Sz_L, to_liouville(ρ; sites=system.sites)))
    for ρ in trajectory_isolated.states_hilbert
]

println("Final ⟨Sz⟩ with the boson = ", last(mz))
println("Final ⟨Sz⟩ for the isolated spin = ", last(mz_isolated))

# The two final values differ because the boson influences the spin. A changed
# trajectory does not, by itself, establish that the influence is non-Markovian.

@assert abs(last(mz) - last(mz_isolated)) > 1e-4

# ## [Closed experiments](@id instrument-schedules)
#
# Each experiment below uses a fresh schedule. `pt` does not change.
# `seq += instrument, step` inserts that instrument at the slot.

# ### Prepare and close the process
#
# Prepare ``|\uparrow\rangle``, the same state used for `evolve`, and trace the final
# output. Every leg is then closed, so
# `evaluate_process` returns a scalar. For this trace-preserving experiment the
# scalar is the total probability, and it is one.

seq_closed = default_schedule(pt)
seq_closed += state_preparation(ρ_up), 0
seq_closed += trace_out(), pt.nsteps

probability = evaluate_process(pt, seq_closed)

println("Closed-process probability:")
println(probability)

@assert probability isa ComplexF64
@assert abs(probability - 1) < 1e-8

# ### Measure a final observable
#
# Replace the final trace by ``S^z``. The scalar is now the expectation value
# ``\operatorname{Tr}(S^z\rho)``, and it matches the last point of `evolve`.

seq_sz = default_schedule(pt)
seq_sz += state_preparation(ρ_up), 0
seq_sz += observable_measurement(Sz), pt.nsteps

sz_final = evaluate_process(pt, seq_sz)

println("Final ⟨Sz⟩ from the schedule:")
println(sz_final)

@assert abs(real(sz_final) - last(mz)) < 1e-8

# ### Insert a control pulse
#
# The process tensor already contains the free spin propagation. An extra
# `unitary_propagation` at one slot is an additional control, not a second copy
# of that free map. The Hamiltonian is applied on the system's Liouville sites.
#
# Compare the final ``S^z`` with and without an ``S^y`` pulse at slot 2. At that
# early slot the spin is still close to ``|\uparrow\rangle``, so an ``S^z``
# pulse would barely move it.

H_pulse = OpSum()
H_pulse += 8.0, "Sy", 1

seq_pulse = default_schedule(pt)
seq_pulse += state_preparation(ρ_up), 0
seq_pulse += unitary_propagation(H_pulse, system.sites), 2
seq_pulse += observable_measurement(Sz), pt.nsteps

sz_pulse = evaluate_process(pt, seq_pulse)

println("Final ⟨Sz⟩ with the pulse:")
println(sz_pulse)
println("Final ⟨Sz⟩ without the pulse:")
println(sz_final)

@assert abs(sz_pulse - sz_final) > 1e-4

# ## Outcomes and open legs

# ### Leave the final output open
#
# `open_output()` does not apply a physical map. It leaves the final reduced
# state uncontracted, which is the same kind of object `evolve` reads along the
# trajectory.

seq_open = default_schedule(pt)
seq_open += state_preparation(ρ_up), 0
seq_open += open_output(), pt.nsteps

ρ_open = evaluate_process(pt, seq_open)

println("Open-output type:")
println(typeof(ρ_open))

ρ_open_L = to_liouville(to_hilbert(ρ_open); sites=system.sites)
sz_open = real(inner(Sz_L, ρ_open_L))

println("⟨Sz⟩ from the open output:")
println(sz_open)

@assert ρ_open isa MPS{Liouville}
@assert abs(tr(to_hilbert(ρ_open)) - 1) < 1e-8
@assert abs(sz_open - last(mz)) < 1e-8

# ### Select one measurement outcome
#
# A spin-up effect is the completely positive map
# ``\rho \mapsto P_\uparrow \rho P_\uparrow``, with
#
# ```math
# P_\uparrow = \tfrac{1}{2}I + S^z.
# ```
#
# The map does not preserve the trace. Closing the process after it returns the
# probability of that outcome, not one.

P_up = OpSum()
P_up += 0.5, "Id", 1
P_up += 1.0, "Sz", 1
P_up_mpo = MPO(P_up, system_sites)
spin_up_effect = left_right_operator(P_up_mpo, P_up_mpo)

seq_outcome = default_schedule(pt)
seq_outcome += state_preparation(ρ_plus), 0
seq_outcome += spin_up_effect, 2
seq_outcome += trace_out(), pt.nsteps

prob_up = evaluate_process(pt, seq_outcome)

println("Probability of spin up at slot 2:")
println(prob_up)

@assert 0 < real(prob_up) < 1

# The instrument above is stored lazily and materialised when the process tensor
# is contracted. A materialised ITensor for the same map represents the same
# intervention; the lazy form is the one used here.

# ### Recover the conditional state
#
# Leave the output open after the same effect. The returned state is
# unnormalised. Its trace is the outcome probability.

seq_conditional = default_schedule(pt)
seq_conditional += state_preparation(ρ_plus), 0
seq_conditional += spin_up_effect, 2
seq_conditional += open_output(), pt.nsteps

ρ_conditional = evaluate_process(pt, seq_conditional)
conditional_trace = tr(to_hilbert(ρ_conditional))

println("Trace of the unnormalised conditional state:")
println(conditional_trace)

@assert ρ_conditional isa MPS{Liouville}
@assert abs(conditional_trace - prob_up) < 1e-8

# ## A causal break
#
# Measuring the spin and then preparing a fresh state breaks the spin's own
# record of its past. Information that remains must sit in the boson.
#
# Use the same spin-up effect, the same repreparation ``|\uparrow\rangle``, and
# the same final ``S^z``. Change only the state prepared at the first slot.

seq_break_plus = default_schedule(pt)
seq_break_plus += state_preparation(ρ_plus), 0
seq_break_plus += observable_measurement(P_up) * state_preparation(ρ_up), 2
seq_break_plus += observable_measurement(Sz), pt.nsteps

seq_break_down = default_schedule(pt)
seq_break_down += state_preparation(ρ_dn), 0
seq_break_down += observable_measurement(P_up) * state_preparation(ρ_up), 2
seq_break_down += observable_measurement(Sz), pt.nsteps

sz_from_plus = evaluate_process(pt, seq_break_plus)
sz_from_down = evaluate_process(pt, seq_break_down)

println("Final ⟨Sz⟩ after a break, prepared in |+⟩:")
println(sz_from_plus)
println("Final ⟨Sz⟩ after a break, prepared in |↓⟩:")
println(sz_from_down)

# The two values differ, so the boson still carries information about the
# earlier preparation. This comparison illustrates that residual influence. It
# is not a complete test of Markovianity.

@assert abs(sz_from_plus - sz_from_down) > 1e-4

# !!! info "Larger experiments to try next"
#     The instruments on this page are the same operations used in the longer
#     examples. Multi-time correlations insert operators at several slots of one
#     process tensor. A tester carries an extra ancilla from one intervention to
#     the next.
#     - [Multi-time correlations](../examples/multitime_correlations.md)
#     - [Noisy quantum circuits with a memory-bearing tester](../examples/noisy_quantum_circuit_tester.md)
#
# !!! related "Related material"
#     - [Construct your first process tensor](@ref) — the spin–boson model used here
#     - Theory: [Process Tensors](../theory/process_tensors.md)
