# Copyright © 2026 Gauthameshwar and ProcessTensors.jl contributors
# SPDX-License-Identifier: MIT
#
# File: src/process_tensor/evolve.jl
# Contributor: Gauthameshwar S.
#
# Implements reduced-system evolution by contracting process tensors with
# instrument schedules.

import ITensors.Ops: Trotter

# Maximally mixed system state |I/d⟩⟩ on a single Liouville process-tensor site.
# Used to CPTP-close future input legs when taking an intermediate marginal on a
# full-length process tensor (see `_evolve_snapshot_seq`).
function _maximally_mixed_liouville(liouv_site::Index)
    d2 = dim(liouv_site)
    d = isqrt(d2)
    d * d == d2 || throw(
        ArgumentError(
            "_maximally_mixed_liouville: expected Liouville dim d^2; got dim=$d2.",
        ),
    )
    mixed = Instruments._vectorized_identity_itensor(Index[liouv_site]) / d
    return _liouville_mps_from_itensor(mixed, Index[liouv_site])
end

"""
    _evolve_snapshot_seq(pt, seq, k; default_instr)

Build the InstrumentSeq whose `evaluate_process` result is the reduced system
state at snapshot `k` (`t = k * dt`, open output leg `out_k`).

Past slots `0:k` are copied from `seq`. The output at time `k` is left open.
Every *future* core is closed with the disconnected CPTP probe
`TraceOut ⊗ StatePreparation(I/d)` so dangling compressed memory bonds
(ACE) are contracted through the remaining influence functional. This is the
same object as the deferred O(N) bond-closure walk in
`notes/deferred_evolve_bond_closures.jl`, evaluated once per snapshot
(O(N²) total).
"""
function _evolve_snapshot_seq(
    pt::ProcessTensor,
    seq::InstrumentSeq,
    k::Int;
    default_instr::AbstractInstrument=_schedule_default_instr(pt),
)
    n = pt.nsteps
    0 <= k < n || throw(BoundsError(0:(n - 1), k))

    snap = InstrumentSeq(default=default_instr, nsteps=n)
    for t in 0:k
        instr = if t == 0
            Instruments.resolve_instrument(seq, 0)
        else
            Instruments.resolve_instrument(seq, t, default_instr)
        end
        instr === nothing && throw(
            ArgumentError(
                "evolve: missing instrument at tstep=$t while building snapshot k=$k.",
            ),
        )
        add!(snap, instr, t)
    end

    if k == n - 1
        add!(snap, open_output(), n)
        return snap
    end

    ρ_mm = _maximally_mixed_liouville(pt.coupling_site)
    # Slot k+1 claims out_k (left open) and closes in_{k+1} with I/d.
    add!(snap, open_output() * state_preparation(ρ_mm), k + 1)
    for t in (k + 2):(n - 1)
        add!(snap, trace_out() * state_preparation(ρ_mm), t)
    end
    add!(snap, trace_out(), n)
    return snap
end

"""
    evolve(pt, seq; default_instr=_schedule_default_instr(pt), alg=Trotter{2}(),
           progress=:auto, verbose=false)

Return reduced system snapshots generated by contracting a process tensor with
an instrument schedule.

Each snapshot `k` is obtained by a separate [`evaluate_process`](@ref) call on
a schedule that copies the past instruments from `seq`, leaves `out_k` open, and
CPTP-closes every future core with `TraceOut ⊗ StatePreparation(I/d)`. This
O(N²) path is the package default so intermediate marginals stay correct for
both Dense and SVD-compressed (ACE) process tensors.

# Examples
```julia
trajectory = evolve(pt, ρ0)
ρ_t = trajectory.states_hilbert[3]
```
"""
function evolve(
    pt::ProcessTensor,
    seq::InstrumentSeq;
    default_instr::AbstractInstrument=_schedule_default_instr(pt),
    alg=Trotter{2}(),
    progress::Union{Bool,Symbol}=:auto,
    verbose::Bool=false,
)
    _validate_instrument_schedule!(pt, seq, default_instr, "evolve")
    started = time()
    run = @progress_start progress verbose "Evolving reduced system" (
        nsteps=pt.nsteps,
        dt=pt.dt,
    )
    try
        # Exactly `nsteps` reduced states: index `j` is the snapshot after PT slab `j-1`
        # (times `t = 0, dt, …, (nsteps-1)*dt`).
        states_liouville = Vector{MPS{Liouville}}(undef, pt.nsteps)
        states_hilbert = Vector{MPO{Hilbert}}(undef, pt.nsteps)
        times = [pt.dt * k for k in 0:(pt.nsteps - 1)]

        @progress_stage run "Preparing trajectory"
        @progress_bar run "Computing reduced snapshots" pt.nsteps begin
            for k in 0:(pt.nsteps - 1)
                snap = _evolve_snapshot_seq(pt, seq, k; default_instr=default_instr)
                rho_liouv = _evaluate_process(
                    pt,
                    snap;
                    default_instr=default_instr,
                    alg=alg,
                    run=_NO_RUN_REPORTER,
                )
                rho_liouv isa MPS{Liouville} || throw(
                    ArgumentError(
                        "evolve: expected MPS{Liouville} at snapshot k=$k; got $(typeof(rho_liouv)).",
                    ),
                )
                states_liouville[k + 1] = rho_liouv
                states_hilbert[k + 1] = to_hilbert(rho_liouv)
                snapshot = k + 1
                @progress_update run snapshot (t=times[snapshot],)
            end
        end
        result = (times=times, states_liouville=states_liouville, states_hilbert=states_hilbert)
        @progress_stage run "Evolved reduced system" (
            nsteps=pt.nsteps,
            dt=pt.dt,
            snapshots=pt.nsteps,
            elapsed_seconds=(time() - started),
        )
        return result
    finally
        @progress_finish run
    end
end

"""
    evolve(pt, rho0, seq; default_instr=_schedule_default_instr(pt))

Insert `state_preparation(rho0)` at `tstep = 0` and return reduced system
snapshots for the resulting schedule.
"""
function evolve(
    pt::ProcessTensor,
    rho0,
    seq::InstrumentSeq;
    default_instr::AbstractInstrument=_schedule_default_instr(pt),
    kwargs...
)
    seq_full = InstrumentSeq(seq.default, seq.nsteps; entries=Dict{Int,AbstractInstrument}(pairs(seq.entries)))
    add!(seq_full, state_preparation(rho0), 0)
    return evolve(pt, seq_full; default_instr=default_instr, kwargs...)
end

"""
    evolve(pt, rho0; default_instr=_schedule_default_instr(pt))

Return reduced system snapshots from an initial state using the default
instrument schedule.
"""
function evolve(
    pt::ProcessTensor,
    rho0;
    default_instr::AbstractInstrument=_schedule_default_instr(pt),
    progress::Union{Bool,Symbol}=:auto,
    verbose::Bool=false,
)
    seq = InstrumentSeq(default=default_instr, nsteps=pt.nsteps)
    add!(seq, state_preparation(rho0), 0)
    return evolve(pt, seq; default_instr=default_instr, progress=progress, verbose=verbose)
end
