# Copyright © 2026 Gauthameshwar and ProcessTensors.jl contributors
# SPDX-License-Identifier: MIT
#
# File: src/process_tensor/evolve.jl
# Contributor: Gauthameshwar S.
#
# Implements reduced-system evolution by contracting process tensors with
# instrument schedules.

import ITensors.Ops: Trotter

# Trace every index except `keep`. Multimode PTs may leave fused bath-memory links
# that must be closed with a fused `vec(I)` rather than a single-site TraceOut.
function _trace_out_except(t::ITensor, keep::AbstractVector{<:Index}; k::Int=0, environment=nothing)
    function _is_fused_bath_link(idx::Index, environment)
        environment isa AbstractBath || return false
        length(environment.modes) > 1 || return false
        "Link" in tag_tokens(idx) || return false
        return dim(idx) == prod(dim(only(mode.sites)) for mode in environment.modes)
    end

    function _fused_bath_trace_itensor(environment::AbstractBath, fused_link::Index)
        bath_sites_prime = prime.([only(mode.sites) for mode in environment.modes])
        comb_primed = combiner(bath_sites_prime...; tags="PT,Link,FusedBath,Prime")
        bath_trace = ITensor(1.0)
        for site in bath_sites_prime
            bath_trace *= Instruments._vectorized_identity_itensor(Index[site])
        end
        return replaceind(bath_trace * comb_primed, combinedind(comb_primed), fused_link)
    end

    keep_vec = Index[keep...]
    out = t
    for idx in inds(out)
        idx in keep_vec && continue
        trace_tensor = if _is_fused_bath_link(idx, environment)
            _fused_bath_trace_itensor(environment, idx)
        else
            Instruments._vectorized_identity_itensor(Index[idx])
        end
        out *= trace_tensor
    end
    return out
end

"""
    evolve(pt, seq; default_instr=_schedule_default_instr(pt), alg=Trotter{2}())

Return reduced system snapshots generated by contracting a process tensor with
an instrument schedule.

The result is a named tuple containing the sample times, Liouville-space
states, and reconstructed Hilbert-space density MPOs.

# Examples
```julia
trajectory = evolve(pt, ρ0)
ρ_t = trajectory.states_hilbert[3]
```
"""
function evolve(
    pt::ProcessTensor,
    seq::InstrumentSeq;
    default_instr::AbstractInstrument=_schedule_default_instr(pt),
    alg=Trotter{2}(),
    kwargs...
)
    _validate_instrument_schedule!(pt, seq, default_instr, "evolve")

    instruments = create_instruments(pt, seq; default=default_instr, alg=alg)

    # Exactly `nsteps` reduced states: index `j` is the snapshot after PT slab `j-1`
    # (times `t = 0, dt, …, (nsteps-1)*dt`).
    states_liouville = Vector{MPS{Liouville}}(undef, pt.nsteps)
    states_hilbert = Vector{MPO{Hilbert}}(undef, pt.nsteps)
    times = [pt.dt * k for k in 0:(pt.nsteps - 1)]

    prev_pt_core = pt.core[1] * instruments[1]

    for k in 0:(pt.nsteps - 1)
        if k > 0
            step = k
            prev_pt_core *= instruments[step + 1]
            prev_pt_core *= pt.core[step + 1]
        end

        out_sites = output_sites(pt, k)
        reduced = _trace_out_except(prev_pt_core, out_sites; k=k, environment=pt.environment)
        rho_liouv = _liouville_mps_from_itensor(reduced, out_sites)
        states_liouville[k + 1] = rho_liouv
        states_hilbert[k + 1] = to_hilbert(rho_liouv)
    end

    return (times=times, states_liouville=states_liouville, states_hilbert=states_hilbert)
end

"""
    evolve(pt, rho0, seq; default_instr=_schedule_default_instr(pt))

Insert `StatePreparation(rho0)` at `tstep = 0` and return reduced system
snapshots for the resulting schedule.
"""
function evolve(
    pt::ProcessTensor,
    rho0,
    seq::InstrumentSeq;
    default_instr::AbstractInstrument=_schedule_default_instr(pt),
    kwargs...
)
    seq_full = InstrumentSeq(seq.default, seq.nsteps; entries=Dict{Int,AbstractInstrument}(pairs(seq.entries)))
    add!(seq_full, StatePreparation(rho0), 0)
    return evolve(pt, seq_full; default_instr=default_instr, kwargs...)
end

"""
    evolve(pt, rho0; default_instr=_schedule_default_instr(pt))

Return reduced system snapshots from an initial state using the default
instrument schedule.
"""
function evolve(
    pt::ProcessTensor,
    rho0;
    default_instr::AbstractInstrument=_schedule_default_instr(pt),
)
    seq = InstrumentSeq(default=default_instr, nsteps=pt.nsteps)
    add!(seq, StatePreparation(rho0), 0)
    return evolve(pt, seq; default_instr=default_instr)
end
